### PR TITLE
json array implicits for doobie

### LINKED ISSUE #111: Add JSON[] and JSONB[] support to doobie module
## Background

At the moment there is no built-in support for arrays containing json data (JSONB[] and JSONB[]) in doobie module. Custom instance of Put and Get typeclasses had to be implemented in AUL in order to allow for functions using these data types. 

Since these data types are widely used in our projects it would be useful to provide instances of necessary type classes as part of the library.

```scala
  import cats.Show
  import cats.data.NonEmptyList
  import doobie._
  import io.circe.{Json, ParsingFailure}
  import doobie.util.Get
  import io.circe.jawn.parse
  import org.postgresql.util.PGobject
  import cats.syntax.all._
  import org.postgresql.jdbc.PgArray

import scala.util.{Failure, Success, Try}

package object functions {

  implicit val jsonbArrayPutUsingCirceJson: Put[List[Json]] = {
    Put.Advanced.other[PGobject](
      NonEmptyList.of("jsonb[]")
    ).tcontramap { a =>
      val o = new PGobject
      o.setType("jsonb[]")
      o.setValue(a.map(_.noSpaces).mkString("{", ",", "}"))
      o
    }
  }

  implicit val jsonbArrayPutUsingString: Put[List[String]] = {
    Put.Advanced.other[PGobject](
      NonEmptyList.of("jsonb[]")
    ).tcontramap { a =>
      val o = new PGobject
      o.setType("jsonb[]")
      o.setValue(a.mkString("{", ",", "}"))
      o
    }
  }

  implicit val jsonbArrayGetUsingCirceJson: Get[List[Json]] = {
    implicit val showPgArray: Show[PgArray] = Show.fromToString

    def parsePgArray(a: PgArray): Either[ParsingFailure, List[Json]] = {
      val array = a.getArray.asInstanceOf[List[String]]
      array.map(e => parse(e)).sequence
    }

    Get.Advanced.other[PgArray](
      NonEmptyList.of("jsonb[]")
    ).temap( a =>
      parsePgArray(a).leftMap(_.show)
    )
  }

  implicit val jsonbArrayGetUsingString: Get[List[String]] = {
    implicit val showPgArray: Show[PgArray] = Show.fromToString

    def parsePgArray(a: PgArray): Either[String, List[String]] = {
      Try(a.getArray.asInstanceOf[List[String]]) match {
        case Failure(exception) => Left(exception.toString)
        case Success(value) => Right(value)
      }
    }

    Get.Advanced.other[PgArray](
      NonEmptyList.of("jsonb[]")
    ).temap( a =>
      parsePgArray(a)
    )
  }

}


  // usage - we have either Option[List[Json]] or List[Json]
  val domainsOption: Option[List[Json]] = ???
  val domains: List[Json] = ???

  // argument to sql function
  domainsOption::JSONB[]
  domains::JSONB[]
```

Doobie currently support provides support only for Json data type from Circe. The above instances will add support for their arrays. The instances can be added also for List[String] provided quotes are properly escaped.

### PR DESCRIPTION
**Pull request by salamonpavel**
Introduced package for postgres related implicits for working with Circe's Json.
Closes #111

### CODE REVIEW

File: doobie/src/main/scala/za/co/absa/db/fadb/doobie/postgres/circe/implicits/package.scala [hunk 1]
```diff
@@ -0,0 +1,95 @@
...
+
+  implicit val jsonArrayGet: Get[List[Json]] = {
+    Get.Advanced
+      .other[PgArray](
+        NonEmptyList.of("json[]")
+      )
+      .temap(pgArray => pgArrayToListOfJson(pgArray))
+  }
+
+  implicit val jsonbArrayPut: Put[List[Json]] = {
```
Comment (lsulak) [inline doobie/src/main/scala/za/co/absa/db/fadb/doobie/postgres/circe/implicits/package.scala:54]: what about JSONB get utils?

File: doobie/src/main/scala/za/co/absa/db/fadb/doobie/postgres/circe/implicits/package.scala [hunk 2]
```diff
@@ -0,0 +1,95 @@
...
+import cats.data.NonEmptyList
+import doobie.{Get, Put}
+import io.circe.Json
+import org.postgresql.jdbc.PgArray
+import org.postgresql.util.PGobject
+import io.circe.parser._
+
+import scala.util.{Failure, Success, Try}
+
+package object implicits {
```
Comment (lsulak) [inline doobie/src/main/scala/za/co/absa/db/fadb/doobie/postgres/circe/implicits/package.scala:29]: also, what about JSON/JSONB put and get? (these here are List of JSON/JSONB, so I'm talking about the non-array variant)

File: demo_database/src/main/postgres/integration/V1.2.18__retrieve_actors_jsonb.sql [hunk 3]
```diff
@@ -0,0 +1,22 @@
...
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+CREATE OR REPLACE FUNCTION integration.retrieve_actors_jsonb(idUntil INT)
+    RETURNS TABLE(actors_jsonb JSONB[]) AS $$
+BEGIN
+    RETURN QUERY SELECT a.actors_jsonb FROM integration.actors_json_seq AS a WHERE id <= idUntil;
```
Comment (lsulak) [inline demo_database/src/main/postgres/integration/V1.2.18__retrieve_actors_jsonb.sql:20]: I like the `<=` idea :)

File: doobie/src/test/scala/za/co/absa/db/fadb/doobie/JsonArrayIntegrationTests.scala [hunk 4]
```diff
@@ -0,0 +1,75 @@
...
+
+class JsonArrayIntegrationTests extends AnyFunSuite with DoobieTest {
+
+  class InsertActorsJson(implicit schema: DBSchema, dbEngine: DoobieEngine[IO])
+    extends DoobieSingleResultFunction[List[Actor], Unit, IO] (
+      values => {
+        val actorsAsJsonList = values.map(_.asJson)
+        Seq(
+          {
+            import za.co.absa.db.fadb.doobie.postgres.circe.implicits.jsonArrayPut
```
Comment (benedeki) [inline doobie/src/test/scala/za/co/absa/db/fadb/doobie/JsonArrayIntegrationTests.scala:39]: Isn't it enough now, to import once and on the top level?

File: doobie/src/main/scala/za/co/absa/db/fadb/doobie/postgres/circe/implicits/package.scala (hunk 2 above)
Comment (salamonpavel) [reply doobie/src/main/scala/za/co/absa/db/fadb/doobie/postgres/circe/implicits/package.scala:29]: the non-array variant is already available, see the docs https://github.com/tpolecat/doobie/blob/v1.0.0-RC2/modules/docs/src/main/mdoc/docs/15-Extensions-PostgreSQL.md

File: doobie/src/test/scala/za/co/absa/db/fadb/doobie/JsonArrayIntegrationTests.scala (hunk 4 above)
Comment (salamonpavel) [reply doobie/src/test/scala/za/co/absa/db/fadb/doobie/JsonArrayIntegrationTests.scala:39]: It would be enough to import it once on the top of the file alongside other imports had we had only json[] or jsonb[]. In this case though we have both and given the way implicits are resolved by their types the compiler is unable to figure out which one to use. That's why in this particular case the imports have to be scope using the curly braces for individual query fragments.

File: doobie/src/main/scala/za/co/absa/db/fadb/doobie/postgres/circe/implicits/package.scala (hunk 1 above)
Comment (salamonpavel) [reply doobie/src/main/scala/za/co/absa/db/fadb/doobie/postgres/circe/implicits/package.scala:54]: It seems to work for both :D

File: doobie/src/main/scala/za/co/absa/db/fadb/doobie/postgres/circe/implicits/package.scala (hunk 2 above)
Comment (lsulak) [reply doobie/src/main/scala/za/co/absa/db/fadb/doobie/postgres/circe/implicits/package.scala:29]: hmm okay! Thanks

File: doobie/src/main/scala/za/co/absa/db/fadb/doobie/postgres/circe/implicits/package.scala (hunk 1 above)
Comment (salamonpavel) [reply doobie/src/main/scala/za/co/absa/db/fadb/doobie/postgres/circe/implicits/package.scala:54]: But I am not against having both defined. Actually let me push it there.

Comment (lsulak) [reply doobie/src/main/scala/za/co/absa/db/fadb/doobie/postgres/circe/implicits/package.scala:54]: really?

because the GET implements `json[]`:

```scala
  implicit val jsonArrayGet: Get[List[Json]] = {
    Get.Advanced
      .other[PgArray](
        NonEmptyList.of("json[]")
      )
      .temap(pgArray => pgArrayToListOfJson(pgArray))
  }
```

perhaps for the sake of consistency in the naming we should either: implement the second one with `jsonb[]` or name this one somehow so that it's understandable that it's also for JSONB GET?

Comment (lsulak) [reply doobie/src/main/scala/za/co/absa/db/fadb/doobie/postgres/circe/implicits/package.scala:46]: discussed on a call

Comment (salamonpavel) [reply doobie/src/main/scala/za/co/absa/db/fadb/doobie/postgres/circe/implicits/package.scala:46]: implemented like this after discussion on a call
```scala
implicit val jsonOrJsonbArrayGet: Get[List[Json]] = {
    Get.Advanced
      .other[PgArray](
        NonEmptyList.of("json[]")
      )
      .temap(pgArray => pgArrayToListOfJson(pgArray))
  }
```

**Review by lsulak — DISMISSED** [review]
I think it's good to go, last few details we discussed on a call. Once the CI checks pass, I'm happy for you to merge it (or wait for someone else from curation for additional review if you want)

**Review by lsulak — DISMISSED** [review]

File: doobie/src/main/scala/za/co/absa/db/fadb/doobie/postgres/circe/implicits/package.scala (hunk 1 above)
Comment (benedeki) [reply doobie/src/main/scala/za/co/absa/db/fadb/doobie/postgres/circe/implicits/package.scala:46]: Somwhat longer but acceptable, IMHO.

**Review by benedeki — DISMISSED** [review]
I believe it's merge-able.
Unless you want to add the code comments, particularly ScalaDoc to the implicits.

File: doobie/src/main/scala/za/co/absa/db/fadb/doobie/postgres/circe/implicits/package.scala (hunk 2 above)
Comment (salamonpavel) [reply doobie/src/main/scala/za/co/absa/db/fadb/doobie/postgres/circe/implicits/package.scala:29]: I've made it available also in the implicits object so we can import everything from the same place.

**Review by lsulak — DISMISSED** [review]

**Review by lsulak — APPROVED** [review]

**Comment by salamonpavel** [comment]
Release notes:
- Introduced implicits for storing and retrieving json and jsonb arrays from postgres using Circe's Json.
