### PR TITLE
86 add prohibited schemas

### LINKED ISSUE #86: Some schemas need special handling
## Background
Some schemas need special handling. Like not changing owner, not clearing existing functions.

## Feature
* Schema `public` should not change owner and not clear all functions, Only those that are being created.
* Schema `pg_toast` should be off-limit (fail if referenced)

If some other limitations come to your mind, add them. 😉

### PR DESCRIPTION
**Pull request by Zejnilovic**
Closes #86

### CODE REVIEW

**Comment by jakipatryk** [comment]
I think this is not essential atm so maybe lets do it after the hackathon

**Review by lsulak — APPROVED** [review]

**Comment by lsulak** [comment]
LGTM, nice safety measures

File: ultet/src/main/scala/za/co/absa/ultet/dbitems/DBSchema.scala [hunk 1]
```diff
@@ -16,17 +16,38 @@
...
+      )
+    }
   }
 }
+
+object DBSchema{
+  private val logger = Logger(getClass.getName)
+
+  val DO_NOT_TOUCH: Seq[String] = Seq("pg_toast", "pg_catalog", "information_schema")
+  val DO_NOT_CHOWN: Seq[String] = Seq("public")
```
Comment (dk1844) [inline ultet/src/main/scala/za/co/absa/ultet/dbitems/DBSchema.scala:52]: I don't think that these vals conform to Scala naming conventions. Perhaps `DoNotTouch` etc?

**Review by dk1844 — APPROVED** [review]
LGTM

File: ultet/src/main/scala/za/co/absa/ultet/dbitems/DBSchema.scala [hunk 2]
```diff
@@ -16,17 +16,38 @@
...
-      SchemaCreate(name),
-      SchemaOwner(name, ownerName),
-      SchemaGrant(name, users)
-    )
+    if (DO_NOT_TOUCH.contains(name.value)) {
+      throw new Exception(s"Schema ${name.value} is not allow to be referenced")
+    }
+
+    if (DO_NOT_CHOWN.contains(name.value)){
+      logger.warn(s"Schema ${name.value} is not allowed to change owner")
```
Comment (benedeki) [inline ultet/src/main/scala/za/co/absa/ultet/dbitems/DBSchema.scala:33]: This will print a warning anytime we have something in `public` schema. But OK for now.

**Review by benedeki — APPROVED** [review]
